language: node_js
node_js:
- '0.10'
install: npm install; npm install bower; bower install
script: ember build --environment production
deploy:
  provider: s3
  access_key_id: AKIAJGEEMQG3JBBJ4FTA
  secret_access_key:
    secure: VRHAd8VQryfQb1L7oiewP68JT09UMxbNYDmocTHXnbeWsclgHx+b364miNHsE32Zz04PVatksFXjZjdSdkfI148t71q+J2j5TyXunrBkPStnh/0hQOKicULWuLjKtbjaoCy3OAIDqge3l7xAnCCrurJUV2Z638cmoyU6a6d9sM0=
  bucket: redgate.ventures
  endpoint: redgate.ventures.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  local-dir: dist
  skip_cleanup: true
